  import fs from 'fs';
  
  const tables = [
  {
    name: "study",
    columns: [
      { name: "name", type: "string", notNull: true, defaultValue: "Untitled" },
      { name: "owner", type: "string" },
      { name: "public", type: "bool", defaultValue: "false" },
      { name: "starred", type: "bool", defaultValue: "false" },
      { name: "passage", type: "text", notNull: true, defaultValue: "1" },
      { name: "model", type: "bool", defaultValue: "false" },
      { name: "metadata", type: "json", defaultValue: "{}" },
      { name: "book", type: "text" },
      { name: "notes", type: "text" },
    ],
    revLinks: [
      { column: "studyId", table: "styling" },
      { column: "studyId", table: "stropheStyling" },
      { column: "studyId", table: "stanzaStyling" },
    ],
  },
  {
    name: "styling",
    columns: [
      { name: "studyId", type: "link", link: { table: "study" } },
      { name: "colorFill", type: "string" },
      { name: "borderColor", type: "string" },
      { name: "textColor", type: "string" },
      { name: "hebId", type: "int", notNull: true, defaultValue: "0" },
      { name: "numIndent", type: "int", defaultValue: "0" },
      { name: "indented", type: "bool", defaultValue: "false" },
      { name: "stropheDiv", type: "bool" },
      { name: "lineBreak", type: "bool" },
      { name: "stanzaDiv", type: "bool" },
    ],
  },
  {
    name: "stropheStyling",
    columns: [
      { name: "studyId", type: "link", link: { table: "study" } },
      { name: "colorFill", type: "text" },
      { name: "borderColor", type: "text" },
      { name: "stropheId", type: "int", notNull: true, defaultValue: "0" },
      { name: "expanded", type: "bool", defaultValue: "true" },
    ],
  },
  {
    name: "stanzaStyling",
    columns: [
      { name: "studyId", type: "link", link: { table: "study" } },
      { name: "expanded", type: "bool" },
      { name: "stanzaId", type: "int", notNull: true, defaultValue: "0" },
    ],
  },
  {
    name: "heb_bible_old",
    columns: [
      { name: "hebId", type: "int" },
      { name: "hebUnicode", type: "string" },
      { name: "book", type: "string" },
      { name: "chapter", type: "int" },
      { name: "verse", type: "int" },
      { name: "strongNumber", type: "float" },
      { name: "wlcWord", type: "string" },
      { name: "gloss", type: "string" },
      { name: "WLCsort", type: "int" },
      { name: "morphology", type: "string" },
      { name: "stropheBreak", type: "bool" },
      { name: "verseBreak", type: "bool" },
      { name: "poetryMarker", type: "bool" },
      { name: "paragraphMarker", type: "bool" },
      { name: "BSBnewStanza", type: "bool" },
      { name: "ETCBCgloss", type: "string" },
    ],
  },
  {
    name: "heb_bible",
    columns: [
      { name: "hebId", type: "int" },
      { name: "book", type: "string" },
      { name: "chapter", type: "int" },
      { name: "verse", type: "int" },
      { name: "wlcWord", type: "string" },
      { name: "hebUnicode", type: "string" },
      { name: "strongNumber", type: "float" },
      { name: "gloss", type: "string" },
      { name: "morphology", type: "string" },
      { name: "WLCsort", type: "int" },
      { name: "poetryMarker", type: "bool" },
      { name: "paragraphMarker", type: "bool" },
      { name: "xatacreatedAt", type: "datetime" },
      { name: "xataupdatedAt", type: "datetime" },
      { name: "xataversion", type: "int" },
      { name: "stropheBreak", type: "bool" },
      { name: "verseBreak", type: "bool" },
      { name: "BSBnewStanza", type: "bool" },
      { name: "ETCBCgloss", type: "string" },
      { name: "HebSort", type: "float" },
      { name: "BSBSort", type: "float" },
      { name: "Vs", type: "float" },
      { name: "BSBVersion", type: "string" },
      { name: "mergecolumn", type: "float" },
      { name: "BSBnewLine", type: "bool" },
      { name: "motifLink", type: "link", link: { table: "motif" } },
    ],
  },
  {
    name: "motif",
    columns: [
      { name: "categories", type: "multiple" },
      { name: "lemmaLink", type: "link", link: { table: "lexicon" } },
      { name: "relatedStrongCodes", type: "multiple" },
    ],
    revLinks: [
      { column: "motifLink", table: "heb_bible" },
      { column: "motifLink", table: "heb_bible_genesis_and_psalms_old" },
      { column: "motifLink", table: "heb_bible_genesis_and_psalms" },
    ],
  },
  {
    name: "lexicon",
    columns: [
      { name: "gloss", type: "text" },
      { name: "lemma", type: "text" },
    ],
    revLinks: [{ column: "lemmaLink", table: "motif" }],
  },
  {
    name: "stepbible_tbesh",
    columns: [
      { name: "eStrong", type: "text" },
      { name: "dStrong", type: "text" },
      { name: "uStrong", type: "text" },
      { name: "Hebrew", type: "text" },
      { name: "Transliteration", type: "text" },
      { name: "Morph", type: "text" },
      { name: "Gloss", type: "text" },
      { name: "Meaning", type: "text" },
    ],
  },
  {
    name: "heb_bible_genesis_and_psalms_old",
    columns: [
      { name: "hebId", type: "int" },
      { name: "book", type: "text" },
      { name: "chapter", type: "int" },
      { name: "verse", type: "int" },
      { name: "wlcWord", type: "text" },
      { name: "hebUnicode", type: "text" },
      { name: "strongNumber", type: "float" },
      { name: "gloss", type: "text" },
      { name: "morphology", type: "text" },
      { name: "WLCsort", type: "float" },
      { name: "poetryMarker", type: "bool" },
      { name: "paragraphMarker", type: "bool" },
      { name: "stropheBreak", type: "bool" },
      { name: "verseBreak", type: "bool" },
      { name: "BSBnewStanza", type: "bool" },
      { name: "ETCBCgloss", type: "text" },
      { name: "HebSort", type: "float" },
      { name: "BSBSort", type: "float" },
      { name: "Vs", type: "int" },
      { name: "BSBVersion", type: "text" },
      { name: "mergecolumn", type: "float" },
      { name: "BSBnewLine", type: "bool" },
      { name: "motifLink_old", type: "float" },
      { name: "motifLink", type: "link", link: { table: "motif" } },
    ],
  },
  {
    name: "heb_bible_genesis_and_psalms",
    columns: [
      { name: "hebId", type: "int" },
      { name: "book", type: "text" },
      { name: "chapter", type: "int" },
      { name: "verse", type: "int" },
      { name: "wlcWord", type: "text" },
      { name: "hebUnicode", type: "text" },
      { name: "strongNumber", type: "float" },
      { name: "gloss", type: "text" },
      { name: "morphology", type: "text" },
      { name: "WLCsort", type: "float" },
      { name: "poetryMarker", type: "bool" },
      { name: "paragraphMarker", type: "bool" },
      { name: "stropheBreak", type: "bool" },
      { name: "verseBreak", type: "bool" },
      { name: "BSBnewStanza", type: "bool" },
      { name: "ETCBCgloss", type: "text" },
      { name: "HebSort", type: "float" },
      { name: "BSBSort", type: "float" },
      { name: "Vs", type: "int" },
      { name: "BSBVersion", type: "text" },
      { name: "mergecolumn", type: "float" },
      { name: "BSBnewLine", type: "bool" },
      { name: "motifLink_old", type: "float" },
      { name: "motifLink", type: "link", link: { table: "motif" } },
    ],
  },
] as const;

const jsonOutput = JSON.stringify(tables, null, 2);
fs.writeFileSync('restore-schema.json', jsonOutput);